//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Demos.Domains.Core;

namespace Demos.Domains.Entidades {
    public partial class Categoria : Entidad {
        public Categoria() {
            this.Subcategorias = new ObservableCollection<Subcategoria>();
        }


        private int _ProductCategoryID;
        public int ProductCategoryID {
            get => _ProductCategoryID;
            set {
                if (_ProductCategoryID == value) return;
                _ProductCategoryID = value;
                RaiseValidateAndChangedProperty(nameof(ProductCategoryID));
            }
        }

        private string _Name;
        public string Name {
            get => _Name;
            set {
                if (_Name == value) return;
                _Name = value;
                RaiseValidateAndChangedProperty(nameof(Name));
            }
        }

        private System.Guid _rowguid;
        public System.Guid rowguid {
            get => _rowguid;
            set {
                if (_rowguid == value) return;
                _rowguid = value;
                RaiseValidateAndChangedProperty(nameof(rowguid));
            }
        }

        private System.DateTime _ModifiedDate;
        public System.DateTime ModifiedDate {
            get => _ModifiedDate;
            set {
                if (_ModifiedDate == value) return;
                _ModifiedDate = value;
                RaiseValidateAndChangedProperty(nameof(ModifiedDate));
            }
        }

        private ObservableCollection<Subcategoria> _Subcategorias;
        public virtual ObservableCollection<Subcategoria> Subcategorias {
            get => _Subcategorias;
            set {
                if (_Subcategorias == value) return;
                _Subcategorias = value;
                RaiseValidateAndChangedProperty(nameof(Subcategorias));
            }
        }

        protected override List<string> ValidateProperty(string propertyName) {
            List<string> lst = new List<string>();
            switch (propertyName) {
                case "": // Validaciones cruzadas
                    break;
            }
            return lst;
        }

    }
}
