//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Demos.Domains.Core;

namespace Demos.Domains.Entidades {
    public partial class Linea : Entidad {

        private int _SalesOrderID;
        public int SalesOrderID {
            get => _SalesOrderID;
            set {
                if (_SalesOrderID == value) return;
                _SalesOrderID = value;
                RaiseValidateAndChangedProperty(nameof(SalesOrderID));
            }
        }

        private int _SalesOrderDetailID;
        public int SalesOrderDetailID {
            get => _SalesOrderDetailID;
            set {
                if (_SalesOrderDetailID == value) return;
                _SalesOrderDetailID = value;
                RaiseValidateAndChangedProperty(nameof(SalesOrderDetailID));
            }
        }

        private string _CarrierTrackingNumber;
        public string CarrierTrackingNumber {
            get => _CarrierTrackingNumber;
            set {
                if (_CarrierTrackingNumber == value) return;
                _CarrierTrackingNumber = value;
                RaiseValidateAndChangedProperty(nameof(CarrierTrackingNumber));
            }
        }

        private short _OrderQty;
        public short OrderQty {
            get => _OrderQty;
            set {
                if (_OrderQty == value) return;
                _OrderQty = value;
                RaiseValidateAndChangedProperty(nameof(OrderQty));
                RaisePropertyChanged(nameof(LineTotal));
            }
        }

        private int _ProductID;
        public int ProductID {
            get => _ProductID;
            set {
                if (_ProductID == value) return;
                _ProductID = value;
                if (Producto != null && _ProductID != Producto.ProductID) {
                    _Producto = null;
                    RaisePropertyChanged(nameof(Producto));
                }
                RaiseValidateAndChangedProperty(nameof(ProductID));
            }
        }

        private int _SpecialOfferID;
        public int SpecialOfferID {
            get => _SpecialOfferID;
            set {
                if (_SpecialOfferID == value) return;
                _SpecialOfferID = value;
                RaiseValidateAndChangedProperty(nameof(SpecialOfferID));
            }
        }

        private decimal _UnitPrice;
        public decimal UnitPrice {
            get => _UnitPrice;
            set {
                if (_UnitPrice == value) return;
                _UnitPrice = value;
                RaiseValidateAndChangedProperty(nameof(UnitPrice));
                RaisePropertyChanged(nameof(LineTotal));
            }
        }

        private decimal _UnitPriceDiscount;
        public decimal UnitPriceDiscount {
            get => _UnitPriceDiscount;
            set {
                if (_UnitPriceDiscount == value) return;
                _UnitPriceDiscount = value;
                RaiseValidateAndChangedProperty(nameof(UnitPriceDiscount));
                RaisePropertyChanged(nameof(LineTotal));
            }
        }

        private System.Guid _rowguid;
        public System.Guid rowguid {
            get => _rowguid;
            set {
                if (_rowguid == value) return;
                _rowguid = value;
                RaiseValidateAndChangedProperty(nameof(rowguid));
            }
        }

        private System.DateTime _ModifiedDate;
        public System.DateTime ModifiedDate {
            get => _ModifiedDate;
            set {
                if (_ModifiedDate == value) return;
                _ModifiedDate = value;
                RaiseValidateAndChangedProperty(nameof(ModifiedDate));
            }
        }

        private Pedido _Pedido;
        public virtual Pedido Pedido {
            get => _Pedido;
            set {
                if (_Pedido == value) return;
                var anterior = _Pedido;
                _Pedido = value;
                if (_Pedido != null && !_Pedido.Lineas.Contains(this))
                    _Pedido.Lineas.Add(this);
                if (anterior != null && anterior.Lineas.Contains(this))
                    anterior.Lineas.Remove(this);
                RaiseValidateAndChangedProperty(nameof(Pedido));
            }
        }

        private Producto _Producto;
        public virtual Producto Producto {
            get => _Producto;
            set {
                if (_Producto == value) return;
                _Producto = value;
                if (_Producto != null && ProductID != _Producto.ProductID)
                    ProductID = _Producto.ProductID;
                RaiseValidateAndChangedProperty(nameof(Producto));
            }
        }

        public decimal LineTotal => UnitPrice * (1 - UnitPriceDiscount) * OrderQty;

        protected override List<string> ValidateProperty(string propertyName) {
            List<string> lst = new List<string>();
            switch (propertyName) {
                case "": // Validaciones cruzadas
                    break;
            }
            return lst;
        }

    }
}
